const Card = [
  {
    id: "1",
    img: "./Images/pizza1.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 190,
  },
  {
    id: "2",
    img: "./Images/pizza2.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 220,
  },
  {
    id: "3",
    img: "./Images/pizza3.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 300,
  },
  {
    id: "4",
    img: "./Images/pizza4.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
  {
    id: "5",
    img: "./Images/pizza5.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 200,
  },
  {
    id: "6",
    img: "./Images/pizza6.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
  {
    id: "7",
    img: "./Images/pizza7.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 300,
  },
  {
    id: "8",
    img: "./Images/pizza8.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
  {
    id: "9",
    img: "./Images/pizza1.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 350,
  },
  {
    id: "10",
    img: "./Images/pizza2.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
  {
    id: "11",
    img: "./Images/pizza3.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 350,
  },
  {
    id: "12",
    img: "./Images/pizza4.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 200,
  },
  {
    id: "13",
    img: "./Images/pizza1.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 190,
  },
  {
    id: "14",
    img: "./Images/food9.jpg",
    alt: "Tandoori Chicken",
    name: "Tandoori Chicken",
    price: 250,
  },
  {
    id: "15",
    img: "./Images/food10.jpg",
    alt: "Chilli Chicken",
    name: "Chilli Chicken",
    price: 250,
  },
  {
    id: "16",
    img: "./Images/pizza2.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 220,
  },
  {
    id: "17",
    img: "./Images/pizza3.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 300,
  },
  {
    id: "18",
    img: "./Images/pizza4.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
  {
    id: "19",
    img: "./Images/pizza5.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 200,
  },
  {
    id: "20",
    img: "./Images/pizza6.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
  {
    id: "21",
    img: "./Images/pizza7.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 300,
  },
  {
    id: "22",
    img: "./Images/pizza8.jpg",
    alt: "Home made pizza",
    name: "Home made pizza",
    price: 250,
  },
];
